image:
  file: .gitpod/Dockerfile
tasks:
  - init: |
      go mod tidy
      go build
      pulumi plugin install resource hcloud 1.3.0
    command: |
      pulumi version
      pulumi login --local
      pulumi stack select -c pulumi-lab-iac-d4l
      pulumi up

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - golang.go
